# Site settings
title: g.js
email: info@nodebox.net
description: A JavaScript library for graphical objects
baseurl: "/g.js/" # the subpath of your site, e.g. /blog/
url: "https://g.js.org/" # the base hostname & protocol for your site
twitter_username: nodebox
github_username:  nodebox
categories: [guide, ref]

# Build settings
markdown: kramdown
